### ISSUE TITLE
Change the radius of Blur

### ISSUE THREAD

**Issue by guotsuan** [chjj/compton#104]
Hi,

I really like the feature of Blur of transparent windows, for example, in the terminal. However, I'm wondering, if it is possible to change the radius of the blur so that the text or patterns in the background image can be heavily smeared.  Thank you very much.

**Comment by Hubro** [comment]
I just happened upon this issue while googling for "compton blurred background". I didn't actually have any hope that it was possible, but to my amazement I found that it was even implemented in the compton version from Debian stretch's package manager.

However, I was going for the "frosted glass" look that's extensively used on iPhone/iOS:

![image](https://user-images.githubusercontent.com/597206/31781602-2a11884a-b4f9-11e7-9d54-94e3410124e2.png)

For this I need more intense blurring, and I've been unable to figure out how to do that with compton. Reading through this issue I'm getting the sense that it's impossible due to performance issues, but I would like to try.

Is this something I might accomplish in Compton if I read up on the blur terminology? (kernel, sigma etc.)

**Comment by raphael141714** [comment]
@Hubro It seems that it's possible in C, according to [this page.](https://graphicdesign.stackexchange.com/questions/20711/how-to-re-create-this-ios7-blur-effect)
You don't have to push it very far : Standard blur (even `3x3box` should do the trick), but you just have to reapply a semi-transparent overlay of the color you want to display.  
So in your example, Apple might only have done one simple gaussian blur on some white background, and then reapplied a white color with 60% opacity on top of it.

**Comment by Hubro** [comment]
@raphael141714 The thing is, all the values I've tried for blur kernel leaves the background far too sharp to achieve the frosted glass effect. In the screenshot above, the background is heavily smeared out.

**Comment by raphael141714** [comment]
This matrix :
`"25,25,0.000338, 0.000404, 0.000476, 0.000552, 0.00063, 0.000708, 0.000784, 0.000854, 0.000917, 0.000968, 0.001006, 0.00103, 0.001038, 0.00103, 0.001006, 0.000968, 0.000917, 0.000854, 0.000784, 0.000708, 0.00063, 0.000552, 0.000476, 0.000404, 0.000338, 0.000404, 0.000483, 0.000569, 0.00066, 0.000754, 0.000848, 0.000938, 0.001022, 0.001097, 0.001158, 0.001204, 0.001233, 0.001243, 0.001233, 0.001204, 0.001158, 0.001097, 0.001022, 0.000938, 0.000848, 0.000754, 0.00066, 0.000569, 0.000483, 0.000404, 0.000476, 0.000569, 0.000671, 0.000778, 0.000888, 0.000999, 0.001105, 0.001204, 0.001292, 0.001364, 0.001419, 0.001452, 0.001464, 0.001452, 0.001419, 0.001364, 0.001292, 0.001204, 0.001105, 0.000999, 0.000888, 0.000778, 0.000671, 0.000569, 0.000476, 0.000552, 0.00066, 0.000778, 0.000902, 0.00103, 0.001158, 0.001282, 0.001397, 0.001498, 0.001582, 0.001645, 0.001684, 0.001698, 0.001684, 0.001645, 0.001582, 0.001498, 0.001397, 0.001282, 0.001158, 0.00103, 0.000902, 0.000778, 0.00066, 0.000552, 0.00063, 0.000754, 0.000888, 0.00103, 0.001176, 0.001323, 0.001464, 0.001595, 0.001711, 0.001807, 0.001879, 0.001923, 0.001938, 0.001923, 0.001879, 0.001807, 0.001711, 0.001595, 0.001464, 0.001323, 0.001176, 0.00103, 0.000888, 0.000754, 0.00063, 0.000708, 0.000848, 0.000999, 0.001158, 0.001323, 0.001487, 0.001645, 0.001793, 0.001923, 0.002031, 0.002112, 0.002162, 0.002179, 0.002162, 0.002112, 0.002031, 0.001923, 0.001793, 0.001645, 0.001487, 0.001323, 0.001158, 0.000999, 0.000848, 0.000708, 0.000784, 0.000938, 0.001105, 0.001282, 0.001464, 0.001645, 0.001821, 0.001984, 0.002129, 0.002248, 0.002338, 0.002393, 0.002412, 0.002393, 0.002338, 0.002248, 0.002129, 0.001984, 0.001821, 0.001645, 0.001464, 0.001282, 0.001105, 0.000938, 0.000784, 0.000854, 0.001022, 0.001204, 0.001397, 0.001595, 0.001793, 0.001984, 0.002162, 0.002319, 0.00245, 0.002547, 0.002607, 0.002628, 0.002607, 0.002547, 0.00245, 0.002319, 0.002162, 0.001984, 0.001793, 0.001595, 0.001397, 0.001204, 0.001022, 0.000854, 0.000917, 0.001097, 0.001292, 0.001498, 0.001711, 0.001923, 0.002129, 0.002319, 0.002488, 0.002628, 0.002732, 0.002797, 0.002819, 0.002797, 0.002732, 0.002628, 0.002488, 0.002319, 0.002129, 0.001923, 0.001711, 0.001498, 0.001292, 0.001097, 0.000917, 0.000968, 0.001158, 0.001364, 0.001582, 0.001807, 0.002031, 0.002248, 0.00245, 0.002628, 0.002775, 0.002886, 0.002954, 0.002977, 0.002954, 0.002886, 0.002775, 0.002628, 0.00245, 0.002248, 0.002031, 0.001807, 0.001582, 0.001364, 0.001158, 0.000968, 0.001006, 0.001204, 0.001419, 0.001645, 0.001879, 0.002112, 0.002338, 0.002547, 0.002732, 0.002886, 0.003001, 0.003072, 0.003096, 0.003072, 0.003001, 0.002886, 0.002732, 0.002547, 0.002338, 0.002112, 0.001879, 0.001645, 0.001419, 0.001204, 0.001006, 0.00103, 0.001233, 0.001452, 0.001684, 0.001923, 0.002162, 0.002393, 0.002607, 0.002797, 0.002954, 0.003072, 0.003144, 0.003169, 0.003144, 0.003072, 0.002954, 0.002797, 0.002607, 0.002393, 0.002162, 0.001923, 0.001684, 0.001452, 0.001233, 0.00103, 0.001038, 0.001243, 0.001464, 0.001698, 0.001938, 0.002179, 0.002412, 0.002628, 0.002819, 0.002977, 0.003096, 0.003169, 0.003194, 0.003169, 0.003096, 0.002977, 0.002819, 0.002628, 0.002412, 0.002179, 0.001938, 0.001698, 0.001464, 0.001243, 0.001038, 0.00103, 0.001233, 0.001452, 0.001684, 0.001923, 0.002162, 0.002393, 0.002607, 0.002797, 0.002954, 0.003072, 0.003144, 0.003169, 0.003144, 0.003072, 0.002954, 0.002797, 0.002607, 0.002393, 0.002162, 0.001923, 0.001684, 0.001452, 0.001233, 0.00103, 0.001006, 0.001204, 0.001419, 0.001645, 0.001879, 0.002112, 0.002338, 0.002547, 0.002732, 0.002886, 0.003001, 0.003072, 0.003096, 0.003072, 0.003001, 0.002886, 0.002732, 0.002547, 0.002338, 0.002112, 0.001879, 0.001645, 0.001419, 0.001204, 0.001006, 0.000968, 0.001158, 0.001364, 0.001582, 0.001807, 0.002031, 0.002248, 0.00245, 0.002628, 0.002775, 0.002886, 0.002954, 0.002977, 0.002954, 0.002886, 0.002775, 0.002628, 0.00245, 0.002248, 0.002031, 0.001807, 0.001582, 0.001364, 0.001158, 0.000968, 0.000917, 0.001097, 0.001292, 0.001498, 0.001711, 0.001923, 0.002129, 0.002319, 0.002488, 0.002628, 0.002732, 0.002797, 0.002819, 0.002797, 0.002732, 0.002628, 0.002488, 0.002319, 0.002129, 0.001923, 0.001711, 0.001498, 0.001292, 0.001097, 0.000917, 0.000854, 0.001022, 0.001204, 0.001397, 0.001595, 0.001793, 0.001984, 0.002162, 0.002319, 0.00245, 0.002547, 0.002607, 0.002628, 0.002607, 0.002547, 0.00245, 0.002319, 0.002162, 0.001984, 0.001793, 0.001595, 0.001397, 0.001204, 0.001022, 0.000854, 0.000784, 0.000938, 0.001105, 0.001282, 0.001464, 0.001645, 0.001821, 0.001984, 0.002129, 0.002248, 0.002338, 0.002393, 0.002412, 0.002393, 0.002338, 0.002248, 0.002129, 0.001984, 0.001821, 0.001645, 0.001464, 0.001282, 0.001105, 0.000938, 0.000784, 0.000708, 0.000848, 0.000999, 0.001158, 0.001323, 0.001487, 0.001645, 0.001793, 0.001923, 0.002031, 0.002112, 0.002162, 0.002179, 0.002162, 0.002112, 0.002031, 0.001923, 0.001793, 0.001645, 0.001487, 0.001323, 0.001158, 0.000999, 0.000848, 0.000708, 0.00063, 0.000754, 0.000888, 0.00103, 0.001176, 0.001323, 0.001464, 0.001595, 0.001711, 0.001807, 0.001879, 0.001923, 0.001938, 0.001923, 0.001879, 0.001807, 0.001711, 0.001595, 0.001464, 0.001323, 0.001176, 0.00103, 0.000888, 0.000754, 0.00063, 0.000552, 0.00066, 0.000778, 0.000902, 0.00103, 0.001158, 0.001282, 0.001397, 0.001498, 0.001582, 0.001645, 0.001684, 0.001698, 0.001684, 0.001645, 0.001582, 0.001498, 0.001397, 0.001282, 0.001158, 0.00103, 0.000902, 0.000778, 0.00066, 0.000552, 0.000476, 0.000569, 0.000671, 0.000778, 0.000888, 0.000999, 0.001105, 0.001204, 0.001292, 0.001364, 0.001419, 0.001452, 0.001464, 0.001452, 0.001419, 0.001364, 0.001292, 0.001204, 0.001105, 0.000999, 0.000888, 0.000778, 0.000671, 0.000569, 0.000476, 0.000404, 0.000483, 0.000569, 0.00066, 0.000754, 0.000848, 0.000938, 0.001022, 0.001097, 0.001158, 0.001204, 0.001233, 0.001243, 0.001233, 0.001204, 0.001158, 0.001097, 0.001022, 0.000938, 0.000848, 0.000754, 0.00066, 0.000569, 0.000483, 0.000404, 0.000338, 0.000404, 0.000476, 0.000552, 0.00063, 0.000708, 0.000784, 0.000854, 0.000917, 0.000968, 0.001006, 0.00103, 0.001038, 0.00103, 0.001006, 0.000968, 0.000917, 0.000854, 0.000784, 0.000708, 0.00063, 0.000552, 0.000476, 0.000404, 0.000338"`
should have done the trick, but compton says it's too big : `parse_matrix(): Matrix width/height too large.`
It corresponds to a 12px radius of gaussian blur.
It has been generated thanks to his : http://dev.theomader.com/gaussian-kernel-calculator/
with a sigma of 8.0

**Comment by marie-bnl** [comment]
So what do you have now ? I'm searching to have the same blur and I have the same error

**Comment by marie-bnl** [comment]
I found the solution, use the tryone's fork https://github.com/tryone144/compton

**Comment by josefwells** [comment]
https://github.com/tryone144/compton does work really well, it is fairly quick/easy to compile, and the performance is better than the 3x3box blur (which is was the fastest I tested on the regular branch, and still pretty laggy)

**Comment by marie-bnl** [comment]
to compile? I installed it from the Arch User Repository XD. But yes it works and it's really easier to use. I also like the render. In a nutshell, I love it

**Comment by josefwells** [comment]
I forked it and opened a pull request for it because there wasnt one previously, maybe it will get accepted and distributed to everyone.
