### ISSUE TITLE
Shadows on Bottom Edge of Maximized Windows

### ISSUE THREAD

**Issue by kenixsis** [chjj/compton#116]
Not really much of an issue and more of a question: is there a way to disable shadows on the bottom edge of maximized windows? I can see the shadow over my bottom panel and while not an inconvenience in any way, it would make it look that much more polished. Thank you for your time.

**Comment by fleutot** [comment]
Is there a way to limit `--shadow-exclude-reg` to only one monitor? What I could read about X's geometry doesn't include `DISPLAY`, X programs have a separate argument for it.

**Comment by fleutot** [comment]
The answer is yes. For two 1920-wide monitors, xmobar on the right:

```
shadow-exclude-reg = "1920x18+1921+0"; # do not draw shadow over xmobar
```

Now I did to detect 1920 automatically, so my `compton.conf` works on multiple resolutions (hints please?).

**Comment by richardgv** [comment]
> Now I need to detect 1920 automatically, so my `compton.conf` works on multiple resolutions (hints please?).

Since `--shadow-exclude-reg` could be specified with a command-line argument, you could simply use `xwininfo` in a command substitution to acquire the geometry of xmobar on the fly:

```sh
compton -c --shadow-exclude-reg "$(xwininfo -name 'xmobar' | pcregrep -o '(?<=^  -geometry ).*')"
```

**Comment by yshui** [comment]
This is so absolutely not the correct way to solve this problem. And this option just have so many way of being abused.

This is terrible. Please think things through before you code.
