### ISSUE TITLE
Disable Compton on xfce screen lock (xflock4)

### ISSUE THREAD

**Issue by stecklars** [chjj/compton#130]
Hi,

I'm using compton on Xubuntu 12.04 LTS and it is great. Finally no more tearing :-)
However when I'm locking the screen (the tool used for this by XFCE is xflock4), it slowly fades black, then the screen comes back (you can see anything again) and immediately fades back to black very fast. That's obviously not the way it is supposed to be ;-)
When Compton is not running it just fades black and stays black, like it is supposed to be.
So I am wondering whether there is some way to deactivate Compton for xflock4 or some other fix?

Thanks!
Lars

**Comment by Hi-Angel** [comment]
@richardgv `compton --fade-exclude 'class_g = "XScreenSaver"'` didn't work — upon running, screensaver is still transparent.

@bwat47 could you say, what's the name for xscreensaver GUI. I remember spent a ½-hour searching what the command's name to install it, to no avail.
