### ISSUE TITLE
No Window Decorations for me

### ISSUE THREAD

**Issue by shillshocked** [chjj/compton#172]
I tried various config files and options. It either would load blank with a cursor or load normally but with no window decorations.

Marco and Compiz work without problems though.

Using Linux Mint 16 MATE on Sandy Bridge 2600K and Asus AMD HD 5850 (currently running on onboard Intel card), upgraded with 3.12.2-031202-generic kernel, and all xorg-xedgers PPA latest graphics stacks/drivers/xserver updates.

**Comment by Pitometsu** [comment]
In Xmonad window decoration broken (gray frame around) by transparency
![transparent][http://i.imgur.com/peuIEoF.png]
![opaque][http://i.imgur.com/D19I4OH.png]
