### ISSUE TITLE
How to disable the shadow drawing when pressing Alt-tab in Marco

### ISSUE THREAD

**Issue by ikem-krueger** [chjj/compton#180]
I'm using LMDE with the MATE desktop environment.

Everytime I hit [alt]+[tab] the highlighted window got an annoying shadow.

I fixed it by adjusting the shadow-exclude part:

shadow-exclude = [
...
"class_g = 'Marco'",
...
];

**Comment by pfalcon** [comment]
> I mean, is this just a tip for us?

It's a hint that it's

> *annoying* shadow

For poor souls who suffer it and for whom the above instructions aren't enough, https://ubuntu-mate.community/t/is-it-possible-to-disable-shadows-with-marco-compton-gpu-compositor/12491/5 has more details, it boils down to having `~/.config/marco-compton.conf` with contents of:

~~~
shadow = false;
~~~

You may want to symlink `marco-compton.conf` to `compton.conf` to make sure that evil is fully exterminated.
