### ISSUE TITLE
Is There A Way To Completely Exclude Applications?

### ISSUE THREAD

**Issue by ghost** [chjj/compton#182]
Hi,

Is there a way to exclude applications with compton? I really don't want Firerfox to have any effects going on with compton, you name it, opacity, shadows, fade, etc., I'd like to be able to have Firefox run without any compton effects if possible?

Thanks...

**Comment by daGrevis** [comment]
Sorry for commenting on an old, closed issue.

    opacity-rule = [
        "99:class_g = 'Firefox'"
    ]

Why 99 instead of 100 and why isn't 100 working?

**Comment by djsavvy** [comment]
Compton ignores values of 100. Unfortunately, with 99, it's still possible to see a tiny bit of transparency.

**Comment by Souravgoswami** [comment]
Hello again, I face problems with firefox.
Now I have both firefox-developer-edition and firefox-nightly.
Using `"class_g='firefox-developer-edtition'"` or `"class_g='Firefox'"` doesn't really work for me.
Also, I can't use `"name~='firefox.*'"`

I am using compton version 7.4.
Please help.

Edit:
using `"name~='Firefox.*'"` solved my issue.

**Comment by PaulPintang** [comment]
> Hello again, I face problems with firefox. Now I have both firefox-developer-edition and firefox-nightly. Using `"class_g='firefox-developer-edtition'"` or `"class_g='Firefox'"` doesn't really work for me. Also, I can't use `"name~='firefox.*'"`
> 
> I am using compton version 7.4. Please help.
> 
> Edit: using `"name~='Firefox.*'"` solved my issue.

not working, any new solution to fix this problem.?
