### ISSUE TITLE
Dmenu transparency

### ISSUE THREAD

**Issue by sac2171** [chjj/compton#257]
I want to have transparency on active windows, transparency on inactive windows, and certain excluded windows. 

So far I have something like this in ~/.compton.conf 
4 # class_g seems to eaual xprop WM_CLASS
  5 opacity-rule = [
  6  "99:class_g = 'Firefox'",
  7  "99:class_g = 'Spotify'",
  8  # For Full Screen Firefox Videos
  9  # Found using `watch -n1 xprop`
 10  "99:class_g = 'Plugin-container'",
 11  "99:class_g = 'flash-plugin'",
 12  "99:class_g = 'dmenu'",                                                                                                                         
 13  "99:class_g = 'Conky'"
 14 ];

Unfortunately, whenever I use xprop, I can't see the window name for dmenu, so I can't figure out how to exclude it from using transparency.

**Comment by richardgv** [comment]
Sorry for the late reply, firstly.

1. I believe dmenu (at least, dmenu-4.5) does not set any properties on its window. (Terrible design, indeed.) You would unfortunately not be able to explicitly match dmenu windows explicitly, without doing some weird things.

2. `--mark-ovredir-focused` will make dmenu windows (and all other override-redirect windows) fully opaque, even if neither `--inactive-opacity` and `--active-opacity` is 1.0 (kind of a hidden rule of compton). Similarity, condition `override_redirect` would work.

3. Should you ever need to explicitly match dmenu windows, you need to patch its source code:

    ```diff
    --- dmenu-4.5/dmenu.c	2012-01-08 20:18:43.000000000 +0800
    +++ dmenu-4.5/dmenu.new.c	2015-01-03 09:16:39.719946115 +0800
    @@ -589,6 +589,21 @@
                            DefaultVisual(dc->dpy, screen),
                            CWOverrideRedirect | CWBackPixel | CWEventMask, &swa);
     
    +	/* Set window properties */
    +	if (win) {
    +		{
    +			char *NAME = "dmenu";
    +			XTextProperty tprop_name;
    +			if (Success == Xutf8TextListToTextProperty(dc->dpy, &NAME, 1,
    +						XStringStyle, &tprop_name))
    +				XSetWMName(dc->dpy, win, &tprop_name);
    +		}
    +		{
    +			XClassHint HINT = { "dmenu", "Dmenu" };
    +			XSetClassHint(dc->dpy, win, &HINT);
    +		}
    +	}
    +
        /* open input methods */
        xim = XOpenIM(dc->dpy, NULL, NULL, NULL);
        xic = XCreateIC(xim, XNInputStyle, XIMPreeditNothing | XIMStatusNothing,
    ```

4. By the way, to get information about windows that grabs pointer, compiling compton with `CPPFLAGS='-DDEBUG_WINDATA' make -B` might help.

**Comment by sac2171** [comment]
Thanks for the detailed information!!
