### ISSUE TITLE
Vsync is broken on 1080p 60fps

### ISSUE THREAD

**Issue by Yanpas** [chjj/compton#277]
Used compton compton "--backend xrender --vsync opengl" and there were no tearing, but 1080p 60 fps videos on Youtube in Chrome are with tearing https://youtu.be/cuXsupMuik4
Using nvidia prorietary 331

**Comment by actionless** [comment]
so with other screen resolution youtube videos are ok?

**Comment by Yanpas** [comment]
No. Tested with different monitor resolutions and video 720p 60fps - the same. Problem is in 60 fps video

**Comment by nopjmp** [comment]
I have the exact same problem with 60fps videos on every backend on my nvidia card. Also all my open programs will stutter when I move them.

**Comment by nopjmp** [comment]
It looks like the latest (beta) nvidia drivers fixed the stutering problem for me except when a window is in front of the 60fps video.

**Comment by NoXPhasma** [comment]
I can't confirm this. Works fine here with Firefox 37 and Chrome 42, with the video of the first post in 1080p@60fps. No matter if I use `--backend xrender --vsync opengl` or `--backend glx --vsync opengl-swc`

Nvidia GTX 660 (prop. driver 346.59)

**Comment by Yanpas** [comment]
If I use --backend glx - everything works good

**Comment by Yanpas** [comment]
https://www.youtube.com/watch?v=cuXsupMuik4&index=4&list=FLUzSXzKitP_li_XVul5kLEg
Test
