### ISSUE TITLE
Bad performance when dragging windows

### ISSUE THREAD

**Issue by dmaarouf** [chjj/compton#279]
I'm using the nvidia proprietrary driver on Arch Linux. My card is the GTX 780. Compton's vsync support and tearing preventing have worked amazingly for me, so scrolling inside windows looks great now, but dragging windows is extremely jumpy and jaggy. When I only have a small, single window open it's pretty much fine, but it gets horrible when there are more than a couple windows on the screen at once. It's especially bad when there are certain windows open like Google Chrome for example which even by itself are extremely laggy when dragged, and cause all other windows on screen to lag terribly when dragged. 

This is what my compton.conf looks like: http://pastebin.com/yJX7CFXg
And my xorg.conf: http://pastebin.com/1FAJCjKM

There's probably a conflicting setting or something that I'm overlooking but I can't figure out what's causing this issue.

Another thing I've noticed, I have a dual monitor configuration, the amount that a window lags appears to depend on how many windows are open on that specific screen, rather than the total number of open windows.

**Comment by actionless** [comment]
is it better if do vsync in videodriver instead of compton?
https://github.com/chjj/compton/issues/227

**Comment by dmaarouf** [comment]
Thanks, adding { ForceFullCompositionPipeline = On } to xorg.conf worked well for me.
