### ISSUE TITLE
Compton wont read symlinked config

### ISSUE THREAD

**Issue by bigmittens** [chjj/compton#281]
I have ~/.dotfiles/compton.conf symlinked to ~/.compton.conf. For some reason compton won't read it:

    $ strace -eopen compton
    ...
    open("/home/user/.compton.conf", O_RDONLY) = -1 ENOENT (No such file or directory)

However, `compton --config .compton.conf` WILL load the config.

I am running the latest version from git on Arch.

**Comment by actionless** [comment]
```sh
$ ll ~/.config/compton.conf
lrwxrwxrwx 1 lie lie 47 Apr 20 12:36 /home/lie/.config/compton.conf -> ../dotfiles/theme-tp-hidpi/.config/compton.conf

$ strace compton ^| grep "compton.conf"
open("/home/lie/.config/compton.conf", O_RDONLY) = 4
```

**Comment by bigmittens** [comment]
Don't know what to say. Getting the same `ll` output.

It immediately starts working if I try the same thing without a symlink. I tried symlinking it in the .config directory too.

**Comment by rr-** [comment]
Works here. I invoke compton in `.xinitrc` like this

    /usr/bin/compton -b --backend glx --paint-on-overlay --vsync opengl-swc

and right after that I run i3wm.

    $ ll ~/.config/compton.conf
    lrwxrwxrwx 1 rr- rr-   43 May  3 23:13 compton.conf -> /home/rr-/src/dotfiles/.config/compton.conf
    $ strace compton 2>&1| grep compton.conf 
    open("/home/rr-/.config/compton.conf", O_RDONLY) = 4
    ^C
    $ compton &
    $ lsof|grep compton|grep conf
    compton   8738       rr-    4r      REG               8,17       41   40243363 /home/rr-/src/dotfiles/.config/compton.conf (deleted)

    $ uname -a
    Linux tornado 4.0.1-1-ARCH #1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux
    $ compton -h|head -n1
    compton (v0.1_beta2)

**Comment by bigmittens** [comment]
Yup. Still same outputs other than the strace. I'm running i3 and Arch 4.0.1 as well. I've added the `--config /home/user/.compton.conf` to .xinitrc for now. Strange though.

**Comment by rr-** [comment]
@bigmittens 
What happens if you do `cat ~/.config/compton.conf`? Perhaps it's your OS that doesn't see it - maybe some weird chmod?

**Comment by bigmittens** [comment]
It's `~/.compton.conf`, but the using `cat` works fine.

**Comment by bigmittens** [comment]
Okay, I just checked again and the compton now finds it without specifying the `--config`. Odd. Closing the issue.
