### ISSUE TITLE
Failed to compile glsl shader with --glx-fshader-win

### ISSUE THREAD

**Issue by jasonMoggridge** [chjj/compton#292]
The command:

    compton --backend glx --force-win-blend --glx-fshader-win "$(cat compton-fake-transparency-fshader-win.glsl)"

Taken from here:
https://github.com/chjj/compton/issues/183

Returns with the error message:

    glx_create_shader(): Failed to compile shader with type 35632: 0:6(11): error: no matching function for call to `texture2D(sampler2D, vec4)'; candidates are:
    0:6(11): error:    vec4 texture2D(sampler2D, vec2)
    0:6(11): error:    vec4 texture2D(sampler2D, vec2, float)

    glx_load_prog_main(): Failed to create GLSL program.

This is with the uneddited compton-fake-transparency-fshader-win.glsl from the main directory of this repository.

If it matters at all, my goal is to make only the black background of certain programs transparent, this seemed to be the way to go.

So far I'm loving compton!
Thanks!

**Comment by jasonMoggridge** [comment]
compton-default-fshader-win.glsl was also affected.

The fix is super simple though, add change `gl_TexCoord[0]` to `gl_TexCoord[0].st` and everything works again.

I found the fix here:
http://wiki.lwjgl.org/wiki/GLSL_Tutorial:_Texturing

The corrected glsl shader:

    uniform float opacity;
    uniform bool invert_color;
    uniform sampler2D tex;

    void main() {
        vec4 c = texture2D(tex, gl_TexCoord[0].st);
        {
                // Change vec4(1.0, 1.0, 1.0, 1.0) to your desired color
                vec4 vdiff = abs(vec4(0.0, 0.0, 0.0, 1.0) - c);
                float diff = max(max(max(vdiff.r, vdiff.g), vdiff.b), vdiff.a);
                // Change 0.8 to your desired opacity
                if (diff < 0.001)
                        c *= 0.1;
        }
        if (invert_color)
                c = vec4(vec3(c.a, c.a, c.a) - vec3(c), c.a);
        c *= opacity;
        gl_FragColor = c;
    }

**Comment by clort81** [comment]
with compton compton --version 0.1~beta2+20150922  i get:

compton --backend glx --force-win-blend --glx-fshader-win keycolor.glsl
glx_create_shader(): Failed to compile shader with type 35632: 0(1) : error C0000: syntax error, unexpected '.', expecting "::" at token "."

glx_load_prog_main(): Failed to create GLSL program.
