### ISSUE TITLE
Penguin Subtitle Player - disabling shadow

### ISSUE THREAD

**Issue by ColdBooted** [chjj/compton#305]
Hey,
This is not an issue but I've been unsuccessful so far in disabling shadow for this app. It has no title bar, wmctrl -lx does not see it among the open windows, the only thing I know from

  xprop WM_CLASS | cut -d\" -f2

is that its class is PenguinSubtitlePlayer. So, how that is done based only on window class info?

![screenshot_2015-09-07_23-22-19](https://cloud.githubusercontent.com/assets/14140205/9749300/06299774-568c-11e5-9cda-96b6130acfa4.png)

**Comment by carsonip** [comment]
Issue on Penguin Subtitle Player repo: https://github.com/carsonip/Penguin-Subtitle-Player/issues/21

**Comment by ColdBooted** [comment]
It is WM_CLASS(0), I've managed to disable shadowing for that particular app with

"class_i = 'PenguinSubtitlePlayer'"
