### ISSUE TITLE
Every pidgin windows share the same active property

### ISSUE THREAD

**Issue by Baspar** [chjj/compton#332]
I have a small issue when using Compton in Openbox, paired with Pidgin.
I've set 2 different opacity for active/inactive windows:

> inactive-opacity = 0.8; 
> active-opacity = 1.0;

It works great, except for Pidgin, where different windows have the same opacity (i.e. if one of them is active, they're all considered as active)
![2016-01-04-184529_1600x900_scrot](https://cloud.githubusercontent.com/assets/8677866/12096129/8b04228c-b313-11e5-9dde-12ab5e34d09b.png)

Configuration:
- compton git-v0.1_beta2-82-gd7f95b5-2015-09-20
- Archlinux
- Pidgin 2.10.12

**Comment by smlx** [comment]
What is your full configuration? Do you have either `detect-transient` or `detect-client-leader` enabled?

**Comment by garnetius** [comment]
Disable `detect-client-leader` in compton.cfg.
