### ISSUE TITLE
how to exclude shadow for firefox smooth scrolling icon?

### ISSUE THREAD

**Issue by adam900710** [chjj/compton#333]
Hi,

Any idea to exclude shadow for firefox smooth scrolling icon?
![2016-01-06-131529_1920x1080_scrot](https://cloud.githubusercontent.com/assets/460269/12135530/edcdcc64-b477-11e5-8eb3-c6b58c61616b.png)

I see some configs just exclude the whole firefox, but at least I want the shadow draw for firefox
main window.
I tried the following config but it excludes all the shadows:
```
shadow-exclude = [
        # Some other working config
        "bounding_shaped"
];
```

Thanks.

**Comment by onodera-punpun** [comment]
I use Compton with shadows, and it doesn't display the square box like on your setup...

**Comment by adam900710** [comment]
@onodera-punpun maybe you are not using clear shadows.
If using normal shadows, there is no such square box as it's filled with shadow.

But that's not a acceptable workaround for me, as my transparent terminal still needs clear shadow.

**Comment by adam900710** [comment]
Finally, I use window_type to match it.
It has UTILITY window type, and I succeded to exclude it now.
