### ISSUE TITLE
Compton not functioning

### ISSUE THREAD

**Issue by Zekario** [chjj/compton#335]
I installed compton fine on my laptop, and it works perfectly. On my desktop, barely anthing happens to show it's working at all; no transparency, only a few shadows (they only appear on i3status, and I disabled them for i3status only because they were annoying). 

My laptop has Intel graphics, and my desktop has open source AMD graphics, could that be it? Can I fix Compton on my desktop, maybe via OpenGL or something?

EDIT: I needed to tell it my config path with `compton --config ~/.compton.conf`. Fixed, anyone can close this now.

**Comment by richardgv** [comment]
Issue closed as requested.

Indeed, the default behavior basically gives the impression that compton is not functioning: compton attempts to act as a drop-in replacement of xcompmgr, and that is how xcompmgr behaves.

`~/.compton.conf` is in the configuration file search path of compton, so it is surprising that you need to manually specify the path. `~/.config/compton.conf` has higher priority over it, though.
