### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by xyproto** [chjj/compton#347]
Hi,

Thanks for making compton. I recently bumped compton from an unofficial package to an official Arch Linux package in [community], due to the popularity and also because it solves a long-standing issue with screen tearing (at least on my systems). It is beautiful.

However, I recently got a feature request for including the 'xrender-sync-fence' options, which I see is in master, but not included in the latest relase.

Could you please make a new release tag which includes 'xrender-sync-fence'? Official Arch Linux packages normally only relates to releases and not specific commits.

Best regards,
Alexander F Rødseth / xyproto

**Comment by onodera-punpun** [comment]
https://github.com/chjj/compton/issues/300

**Comment by xyproto** [comment]
Didn't see that one, even when searching previous issues. Thanks.
