### ISSUE TITLE
Screen tearing in specific applications

### ISSUE THREAD

**Issue by Guanox** [chjj/compton#350]
Hello, for some time I have been experiencing something I would call screen tearing inside chromium and slack. The tearing disappears when I kill compton.

![uname & lsb_release](http://i.imgur.com/SJkpD0H.png)

Here's some pictures of how it appears: 
[pic](http://i.imgur.com/eY8nADA.png )
[pic](http://i.imgur.com/S0ts5UR.png) 
This tearing happens whenever I scroll the content, or move the cursor around inside the application

This picture shows the same application that is affected by the tearing(chromium) but after opening a terminal next to the app,  which changes the aspect ratio of the window the tearing goes away
[pic](http://i.imgur.com/gxZDcFj.png)

**Comment by kelleyk** [comment]
Could you please tell us what video hardware and driver you are using?  What configuration are you using compton with?

**Comment by Guanox** [comment]
Here's my graphics devices
```
~ λ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family integrated Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 540M] (rev a1)
```

Here is graphics drivers that I use
```
~ λ lspci -nnk | grep -i vga -A3 | grep 'in use'
	Kernel driver in use: i915
	Kernel driver in use: nouveau
```

This is my normal start config.
`compton -f -D 4 --no-fading-openclose` or just as default `compton`
Both produces the same results.

**Comment by Guanox** [comment]
It actually works now. I first encountered the problems around a couple months ago, I bet some patch along the way fixed the problem, I got no idea what the fix was.

**Comment by richardgv** [comment]
I am glad that the problem is gone. Issue closed.
