### ISSUE TITLE
Image preview artifacts in ranger with termite when running compton

### ISSUE THREAD

**Issue by gnosticscrounger** [chjj/compton#361]
Whenever I run compton, the image previews on ranger look screwed up and stripped. At first, I thought it was termite's fault as the problem was less pronounced (but still there) when running ranger with urxvt. 

However, I was trying out KDE with openbox as a window manager when I decided to boot up ranger under termite. It struck me that the transparancy that I was used to wasn't there but on top of that, the images were rendering properly!

I then login with awesome wm and decide to try disabling transparancy on termite but the images still failed to render properly. It was only when I turned off compton that they began working as they did under openbox.

I then tried running compton with all shadows disabled with the -CG flag. Still did not work.

I am running the latest stable release of Compton under Archlinux. Should I try the git version?

**Comment by mmedum** [comment]
Hi @gnosticscrounger 

Hit something related, running i3wm with google chrome, some pages is flickering when scrolling and ranger gives screwed images with termite. I used --paint-on-overlay, which helped a little.

**Comment by smlx** [comment]
Does [this](https://github.com/hut/ranger/wiki/Image-Previews#troubleshooting) help?

**Comment by gnosticscrounger** [comment]
I already did that and while it helped with this other problem where part of the terminal window would be missing as the preview pane changes, it did not do anything about the image artifacts.

**Comment by gnosticscrounger** [comment]
I might need to resort to using urxvt for ranger which seems to display the images correctly (though without transparancy). Kind of annoying having to learn a different configuration scheme but should be doable.

**Comment by smlx** [comment]
I thought you said that urxvt also had the issue?

**Comment by gnosticscrounger** [comment]
I did it seems. It was not working back when I made this comment but trying it just now, it seems to be displaying correctly. Not exactly sure why though. I did change my compton configuration in some ways since then which may have been the cause.

**Comment by smlx** [comment]
Since the ranger wiki page mentions that image preview only works in a few terminals (not including termite), I'd say that this isn't a compton bug.

**Comment by gnosticscrounger** [comment]
Yes but it also mentions vte terminals (of which termite is one of)

**Comment by gnosticscrounger** [comment]
Others have experienced this issue with termite and ranger too so I guess you can close this issue
https://github.com/hut/ranger/issues/472

**Comment by gnosticscrounger** [comment]
Replacing the main repo vte-ng with this one fixed it: 
https://aur.archlinux.org/packages/vte3-ng-fullwidth-emoji/

**Comment by gnosticscrounger** [comment]
Whoops, forgot about this issue so I shall close it now.
