### ISSUE TITLE
"Glassy" frame around Nautilus

### ISSUE THREAD

**Issue by Pshemas** [chjj/compton#377]
So far Compton has been almost perfect on my system.
The only issue is a glassy frame around Nautilus file manager. Any suggestions howto get rid of it?
In other cases adding something like shadow-exclude = ["name *= 'Terminix'"] (which fixed it for terminix) worked like a charm , but I can't get it to work with the pesky file manager. My guess is I'm not using the correct name? Any suggestions?

**Comment by Brottweiler** [comment]
Can you show a screenshot? I don't think mine is "glassy"...

**Comment by Pshemas** [comment]
sure:
[img]http://i814.photobucket.com/albums/zz63/pj_pics/various/compton_frame_glass_zpsvcnnrzyc.jpg~original[/img[

as mentioned I got similar effects on Terminix, but as soon as I added :

shadow-exclude = "name *= 'Terminix'"

to the config file those were gone. So I assume I simply don't know howto make Compton exclude Nautilus as well.

**Comment by onodera-punpun** [comment]
This is a problem with gtk3/gnome, because it already uses shadows build in the frame, and compton can't know that.

**Comment by Pshemas** [comment]
but can I exclude nautilus in the same manner I excluded terminix?

**Comment by Pshemas** [comment]
actually the question should be - how should I know what to put in:
shadow-exclude = [
"name = '????????'",
"class_g = '?????????'",]
and what's the difference betwen "name=" , "class_g=" and "name *=", "class_g ?=" 
?

**Comment by smlx** [comment]
Please read the manpage. All those questions (and more!) are answered there...

-- 
Regards,
Scott.

**Comment by Pshemas** [comment]
checked the faq/wiki and haven't found the answer - can you guide me to the page with those anserws?

**Comment by Pshemas** [comment]
ok, so I think I got it - I've added this line to shadow-exclude:

    "WM_CLASS@:s *?= 'Nautilus'",

and it seems to do the trick
