### ISSUE TITLE
URxvt scrolling is laggy when using glx backend

### ISSUE THREAD

**Issue by Quent42340** [chjj/compton#391]
I tried to switch to `compton` from `xcompmgr` recently, but I've some issues which made it quite unusable.

For example, the major issue I have is when I scroll with URxvt, sometimes a line temporarily disappears, or appears twice, like if the bottom of the window was refreshed with a little delay.
With the `xrender` backend I don't have this issue but other issues like with `synapse` for example.

I made a little video thanks to `recordmydesktop` to show the problem (hard to explain with words): [https://www.youtube.com/watch?v=goGpkUSBhv8](https://www.youtube.com/watch?v=goGpkUSBhv8)
(Sorry for the blinks, I don't know if it's related to my issue, another issue or because of `recordmydesktop`)

And here is a screenshot from the video which shows the problem quite well (look at the line numbers + color numbers):
![](http://i.imgur.com/i0OMVme.png)
Here is the file in the screenshot: [https://github.com/Quent42340/dotfiles/blob/master/link/.Xdefaults](https://github.com/Quent42340/dotfiles/blob/master/link/.Xdefaults)

Here is my config file (even though the problem persists without it): [https://github.com/Quent42340/dotfiles/blob/master/link/.config/compton/compton.conf](https://github.com/Quent42340/dotfiles/blob/master/link/.config/compton/compton.conf)

And here is my `/etc/X11/xorg.conf.d/20-intel.conf`: [http://pastebin.com/12sDeNFU](http://pastebin.com/12sDeNFU)

I'm running ArchLinux x86_64 with the last compton version available on the `community` repository.

**Comment by kilbith** [comment]
I may have met the same issue. Are you using `xf86-video-intel` ? Can you try with the modesetting driver instead ? (just remove the Intel driver).

**Comment by Quent42340** [comment]
The X server fails to load when I remove `xf86-video-intel`. :/

**Comment by kilbith** [comment]
The modesetting driver only supports DRI3, so you may need to edit `20-intel.conf` accordingly. Also, any relevant log in `systemctl` ?

**Comment by Quent42340** [comment]
Ok I removed this file and reboot, it worked. Compton worked fine without the `xf86-intel-driver`

**Comment by 0x041E** [comment]
@Quent42340 Did you try adding xrender-sync-fence = true; to your config file? For me it fixed some redraw issues with intel driver

**Comment by Quent42340** [comment]
I tried it before, didn't work, but now for some reason it worked, so thanks.
