### ISSUE TITLE
[Question] Compton causes strange Game lag in full screen TF2. What switches are needed?

### ISSUE THREAD

**Issue by BurningSmile** [chjj/compton#393]
I have narrowed the cause on my i3 setup to be Compton. Some things that were suggested that I have tried are as follows.

in the i3 config I exec Compton with the following switches

exec compton --backend xrender --vsync none

I also did as requested and edited my xorg.conf file with the following parameter on the metamode line under display. This was done for all screens.

{ForceFullCompositionPipeline=On}

When starting i3 without Compton the game runs fine just to verify the cause is Compton.

My GPU is a  Nvidia 1080

Thanks!

**Comment by Ufeldraku** [comment]
--vsync can be anything you want, however, you need to add --unredir-if-possible.  
For more options, you can use compton -h
