### ISSUE TITLE
Built-in blur kernels are missing?

### ISSUE THREAD

**Issue by sphaugh** [chjj/compton#417]
I can put 

```
21 blur-background = true;
22 blur-background-frame = true;
23 blur-kern = 7x7box;
```

in my `compton.conf` and I get

```
Error when reading configuration file "/home/sean/.config/compton.conf", line 23: syntax error
```

It works if I generate the kernel manually... what gives?

**Comment by ghost** [comment]
I realized a while ago that this needs to be a quoted string like `blur-kern = "7x7box";`. My bad :)
