### ISSUE TITLE
How to use `--glx-fshader-win` ?

### ISSUE THREAD

**Issue by vn971** [chjj/compton#419]
Is the `--glx-fshader-win` flag broken? Or how does it work? I'm trying to do:

`LANG=en_US.UTF-8 compton --glx-fshader-win compton-default-fshader-win.glsl`

but it doesn't work, it shows an error:

```text
glx_create_shader(): Failed to compile shader with type 35632: 0:1(1): error: syntax error, unexpected NEW_IDENTIFIER

glx_load_prog_main(): Failed to create GLSL program.
```

I get the same error no matter what glsl program I try to compile (including a empty 0-byte program, all built-in ones).

**Comment by vn971** [comment]
I'm using the latest commit: b7f43ee67a1d2d08239a2eb67b7f50fe51a592a8

**Comment by kurnevsky** [comment]
I managed to load it: compton --glx-fshader-win "$(cat compton-default-fshader-win.glsl)"

**Comment by vn971** [comment]
ah, you have to specify the contents. Closing the ticket, then.
