### ISSUE TITLE
Trouble getting shadow to be perfectly centered behind window

### ISSUE THREAD

**Issue by Brett99** [chjj/compton#428]
I would like the shadow to extend the same amount in all directions, as if the light is in the center of the window. Changing the x and y offset to 2, 1, 1/2, 1/4  of the radius don't seem to do the trick. What numbers should I use to do this? Is there an easier way?

Why isn't an offset of (0,0) centered directly behind the window?

**Comment by Brett99** [comment]
I ended up finding that to center shadows, the x and y offset should be r * -1.5

**Comment by TWB0109** [comment]
> I ended up finding that to center shadows, the x and y offset should be r * -1.5

So, this means the shadow radius multiplied by -1.5?
