### ISSUE TITLE
xprop not being detected by compton-trans

### ISSUE THREAD

**Issue by rieje** [chjj/compton#429]
Platform: Arch Linux

Compton version: 0.1_beta2.5-5

When executing `compton-trans -n "termite" -o 80`, The following error results:

> The command xwininfo or xprop is not available. They might reside in a package named xwininfo, xprop, x11-utils, xorg-xprop, or xorg-xwininfo.

The command should detect that xprop is installed: 
`which xprop`
> /usr/bin/xprop

**Comment by richardgv** [comment]
Please make sure you have `xwininfo` in your `$PATH` as well. `compton-trans` requires both `xwininfo` and `xprop` to work properly, and I do not think there is a need to detect which tool is missing specifically.

**Comment by rieje** [comment]
@richardgv Thanks---installed `xwinfo` and now `compton-trans -w "<$ID>" 50` works; however, I'm trying to create a script that sets all my terminal windows to a specified level of opacity. `compton-trans -n "termite" 80` does not appear to do anything and the command does not complete. `termite` is the string from the output of `xinwinfo`: `xwininfo: Window id: 0x2200003 "termite"`.
