### ISSUE TITLE
Can't record desktop with compton active

### ISSUE THREAD

**Issue by justUmen** [chjj/compton#438]
Recording doesn't work with `compton` activated. (no problem with `xcompmgr`)

Example :
`ffmpeg -f x11grab -i :0 whatever.mp4`
(`recordmydesktop` and others, have the same problem)
It took me a while to pin point the fact that `compton` was the perpetrator...

Platform: Archlinux
Compton version: v0.1_beta2.5 (from repo)

**Comment by erikdubois** [comment]
it may not answer your question
i use simplescreenrecorder

**Comment by kmatheussen** [comment]
No problem recording with OBS: https://obsproject.com/
(This is by far the best recording software too, at least that was my
conclusion last year)

**Comment by ghost** [comment]
odd, no issues with recordmydesktop/ffmpeg and compton here. What is the actual problem, any logs?

**Comment by user827** [comment]
Do you have paint-on-overlay on? Turning it off should be one way to fix it.

**Comment by justUmen** [comment]
I'm back now on `compton` on a different PC and it works fine.
Driver issue ? An update fixed it ? not sure.
Anyway case closed. ;)
