### ISSUE TITLE
ICC Color Management

### ISSUE THREAD

**Issue by Popkultur** [chjj/compton#443]
Hello,

I'd like to see the ability to use ICC color profiles with compton. Maybe using colord.

**Comment by SammysHP** [comment]
That is totally unrelated to compton. You need a loader that loads the calibration into the graphics card (e.g. dispwin from argyll cms) and color managed applications for the profile.

**Comment by Popkultur** [comment]
yeah, you are right (I just thought about having correct colors for the GUI on wide gamut displays. So the compositor came to my mind somehow.)
