### ISSUE TITLE
compton and delayed window movments

### ISSUE THREAD

**Issue by z0id5** [chjj/compton#45]
Hello.

I have recently istalled compton on 2 computers which run Debian squeeze LXDE: a netbook and a laptop. On the netbook it works like a charm. On my laptop I am facing an issue: 

When I am moving a window with a mouse cursor the window movement is delayed related to the cursor. I had exactly the same window movement delay issue (not compton-related) using another distro right before installing the graphics card driver (nvidia). I have currently an nvidia driver installed on my laptop and the window movements are normal when compton is turned off.

I was running the simple autostart compton command "@compton -cC -i 0.6 -e 0.6".

Any ideas for a fix?

Thanks in advance for any help.

**Comment by kq01526** [comment]
@richardgv :

I've got the exact same issue using XFCE4 with xfwm4 as the window manager and Compton as the compositor, running on an Intel Core i7-6700K.

I'm using the following version of Compton:

http://packages.ubuntu.com/xenial/compton

I've tried compton with:

`compton -b --paint-on-overlay --backend=glx --glx-swap-method=buffer-age`

and:

`compton -b --paint-on-overlay --backend=glx --glx-swap-method=exchange`

as suggested over there:

https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/911776-amdgpu-radeon-ddx-updated-better-2d-performance-tear-free-dri3-default?p=914343#post914343

When dragging windows around, the windows are lagging behind the mouse cursor noticeably.

Tried it with xf86-video-intel and with xf86-video-modesetting, but no difference.

When running GNOME 3 with Mutter as the window manager and compositor, it's a lot better. And when running GNOME 3 on Wayland (Fedora), it's *way* better :slightly_smiling_face: (with Wayland it's actually pretty much perfect).

Do you have any suggestions on how it could be improved when running Compton?
