### ISSUE TITLE
Weird Black Pixels after lock/unlock

### ISSUE THREAD

**Issue by Drakota** [chjj/compton#459]
Platform: Arch Linux x86_64 Linux 4.13.9-1-ARCH

GPU, drivers, and screen setup: GeForce GTX 960M 387.22

Compton version: compton (v0.1_beta2.5)

Compton configuration: https://gist.github.com/Drakota/af65cf3e53d6687213dfec6d3e74f685

### Steps of reproduction
Lock Screen using light-locker-command -l
Unlock Screen and get black pixel that has to be removed my moving a window.

### Current Behavior & Other details

![screenshot from 2017-11-07 15-53-14](https://user-images.githubusercontent.com/22665836/32517590-e3da948a-c3d4-11e7-9caf-9821a471a6b6.png)
I get this weird black pixels that can be "swiped" by moving a window. If I tried killing compton while I have this black stuff it removes it and works has intented. I tried removing compton from my I3WM config and lock/unlock and I do not get this, why?

**Comment by 0x041E** [comment]
did you try `glx-copy-from-front = false;` and changing `glx-swap-method` ?
