### ISSUE TITLE
How can I make compton not transparentize or diminish certain window (rofi)

### ISSUE THREAD

**Issue by amosbird** [chjj/compton#463]
`rofi` doesn't ever become focused, and i don't want it be treated like inactive by compton. What can I do? Thanks!

**Comment by dieggsy** [comment]
@amosbird did you make any progress with this?

**Comment by dieggsy** [comment]
Huh - immediately after asking I found this: https://github.com/DaveDavenport/rofi/wiki/Using-rofi-with-compton

**Comment by amosbird** [comment]
Great find!

**Comment by dieggsy** [comment]
@amosbird note the rule can also be added to the `focus-exclude` list in compton.conf
