### ISSUE TITLE
xrender makes screen tearing worse

### ISSUE THREAD

**Issue by Brottweiler** [chjj/compton#471]
- **Platform**: Archlinux
- **GPU, drivers, and screen setup**: GeForce GTX 750 Ti, nvidia-drivers `387.34`, one monitor
- **Compton version**: `0.1_beta2.5-10`
- **Compton configuration**: `compton --config /dev/null --backend xrender -b &!`

### Steps of reproduction

Check tearing without compton, run command above and compare, with a [video](https://youtu.be/gmHaa5pvpVc) maybe.

### Expected behavior

Tearing should remain the same as before launching compton.

### Current Behavior & Other details

Tearing gets even worse, there's a clear tearing line on the screen way worse and way more noticable than it was without compton running. I suppose without compton there's less noticable tearing in several places, but with compton i get _one_ noticable line on the screen.

Running it with `--vsync opengl` removes the normal subtle tearing, but the main big tear I'm talking about is still present. 

This type of tear I experience is also present when running OBS Studio, xcomposite source to record a X window.

-----

Does anyone recognize this issue?

**Comment by Mukundan314** [comment]
Is this same as #376.

**Comment by Brottweiler** [comment]
I don't think it's the same. Why do you think it is?
