### ISSUE TITLE
rofi rendering artefacts on GLX backend

### ISSUE THREAD

**Issue by Coffei** [chjj/compton#475]
Platform: Fedora 27

GPU, drivers, and screen setup: Intel integrated gpu (Intel Corporation HD Graphics 620), 

Compton version: 0.1_beta3-1 installed from axeld/compton COPR
rofi version: 1.4.1

Compton configuration: reproducible with `compton -f --backend glx --config /dev/null`

### Steps of reproduction
run rofi (https://github.com/DaveDavenport/rofi) with and without compton with GLX backend and observe the visual differences.

### Current Behavior & Other details
Screenshots I made: https://imgur.com/a/Z5bmx

The colors are all different and there are also some visual glitches when moving around, it looks like the previous frame is rendered in the current one or something.

Note this doesn't happen with `xrender` backend, however I wasn't able to get rid of screen tearing with that backend, so I want to use `GLX`. I also tried a bunch of switches from the documentation, like `-glx-no-stencil --glx-copy-from-front --force-win-blend --paint-on-overlay --sw-opti --vsync --detect-client-opacity` in different combinations but observed no difference.

### Expected behavior
rofi should render the same way with/without compton and with `xrenderx` and `GLX` backends.

**Comment by ghost** [comment]
Am facing this issue too, with the glx backend, have attempted the same measures, have included rofi in `focus-exclude` in the `compton.conf` file as well, as well as set `opacity-rule` for rofi to 0.9, nothing seems to work.
PFA screenshots of this issue:
Without compton
![screenshot_20180203_170737](https://user-images.githubusercontent.com/15681865/35772066-df2b3f5e-0905-11e8-9032-1d6d2fabe600.png)
With compton
![screenshot_20180203_170951](https://user-images.githubusercontent.com/15681865/35772069-e4385f9a-0905-11e8-9233-6f57ddae4765.png)

**Comment by valsoray17** [comment]
The same issue here. Using "xr_glx_hybrid" backend draws rofi correctly, but it takes ~1 sec to show rofi window. So not the best solution...

**Comment by ollien** [comment]
Is there any update on this? I'm still experiencing problems. "xr_glx_hybrid" doesn't fix much, and having to live with screen tearing is really getting on my nerves.

**Comment by ollien** [comment]
Looks like this might have been a mesa bug.

I updated my system today, and the issue went away. Here's the relevant portion of my dnf log

```
[~] nick@bender$ sudo dnf history info 244 |grep -A 1 mesa
    Upgraded mesa-dri-drivers-17.2.4-3.fc27.i686                             @updates
    Upgraded mesa-dri-drivers-17.2.4-3.fc27.x86_64                           @updates
    Upgrade                   17.3.5-1.fc27.i686                             @updates
--
    Upgraded mesa-filesystem-17.2.4-3.fc27.i686                              @updates
    Upgraded mesa-filesystem-17.2.4-3.fc27.x86_64                            @updates
    Upgrade                  17.3.5-1.fc27.i686                              @updates
--
    Upgraded mesa-libEGL-17.2.4-3.fc27.i686                                  @updates
    Upgraded mesa-libEGL-17.2.4-3.fc27.x86_64                                @updates
    Upgrade              17.3.5-1.fc27.i686                                  @updates
--
    Upgraded mesa-libEGL-devel-17.2.4-3.fc27.x86_64                          @updates
    Upgrade                    17.3.5-1.fc27.x86_64                          @updates
    Upgraded mesa-libGL-17.2.4-3.fc27.x86_64                                 @updates
    Upgrade             17.3.5-1.fc27.x86_64                                 @updates
    Upgraded mesa-libGL-devel-17.2.4-3.fc27.x86_64                           @updates
    Upgrade                   17.3.5-1.fc27.x86_64                           @updates
    Upgraded mesa-libOpenCL-17.2.4-3.fc27.x86_64                             @updates
    Upgrade                 17.3.5-1.fc27.x86_64                             @updates
    Upgraded mesa-libgbm-17.2.4-3.fc27.i686                                  @updates
    Upgraded mesa-libgbm-17.2.4-3.fc27.x86_64                                @updates
    Upgrade              17.3.5-1.fc27.i686                                  @updates
--
    Upgraded mesa-libglapi-17.2.4-3.fc27.i686                                @updates
    Upgraded mesa-libglapi-17.2.4-3.fc27.x86_64                              @updates
    Upgrade                17.3.5-1.fc27.i686                                @updates
--
    Upgraded mesa-libwayland-egl-17.2.4-3.fc27.i686                          @updates
    Upgraded mesa-libwayland-egl-17.2.4-3.fc27.x86_64                        @updates
    Upgrade                      17.3.5-1.fc27.i686                          @updates
--
    Upgraded mesa-libwayland-egl-devel-17.2.4-3.fc27.x86_64                  @updates
    Upgrade                            17.3.5-1.fc27.x86_64                  @updates
    Upgraded mesa-libxatracker-17.2.4-3.fc27.x86_64                          @updates
    Upgrade                    17.3.5-1.fc27.x86_64                          @updates
```

**Comment by ghost** [comment]
@ollien Yep, checked my Fed27 install after updating too, seems to work fine now.
Cheers!

**Comment by Coffei** [comment]
Latest update also fixed it for me on Fedora 27. 
Since most users who reported this issue are no longer experiencing it after system update I am closing the ticket.
