### ISSUE TITLE
Feature Request: Not draw anything over a fullscreen window

### ISSUE THREAD

**Issue by diamondburned** [chjj/compton#481]
Hello. I have `--unredir-if-possible` under `compton`'s options. It works well until some notification pops up which enables VSync for the game I'm playing. It's really annoying, so I thought that a feature to prevent any drawing over the fullscreen would be a good idea.

**Comment by ghost** [comment]
A possible workaround for now would be to set up a keybind in your window manager to toggle your notification daemon on and off.

**Comment by smlx** [comment]
This is a limitation of X11. Unfortunately there is no way for compton to stop a notification window from drawing on top of it.
