### ISSUE TITLE
Include applications to Shadows and Blur instead of excluding

### ISSUE THREAD

**Issue by ghost** [chjj/compton#484]
Is there any way to whitelist programs for shadowing and blurring instead of blacklisting? If not, I suggest the addition of the ability to use the syntax "shadow-include = [ ]"

**Comment by fauu** [comment]
The following works for me:
`blur-background-exclude = "(!window_type = 'dock' && !name = 'rofi' && !class_g = 'Alacritty')"`

**Comment by thenoobtester** [comment]
I would love this too!
