### ISSUE TITLE
No option to set mouseover windows opacity

### ISSUE THREAD

**Issue by Dr-Dd** [chjj/compton#485]
Is there any way to change the mouseover windows' opacity? Right now it's too transparent and i can't find a way to change it from the compton.conf file.

**Comment by tesuji** [comment]
@Dr-Dd Could you give a screenshot?

**Comment by Dr-Dd** [comment]
![screenshot_2018-04-07_19-20-34](https://user-images.githubusercontent.com/37450282/38458069-99cfec64-3a99-11e8-84e5-63f34b5a68d9.png)

The screenshot above is a worst case scenario, but happens more often than it should.

**Comment by tesuji** [comment]
Try to add these into your `~/.config/compton.conf`:

```bash
# Window type settings
######################

wintypes:
{
    tooltip =
    {
        # fade: Fade the particular type of windows.
        fade = false;
        # shadow: Give those windows shadow
        shadow = false;
        # opacity: Default opacity for the type of windows.
        opacity = 1;
        # focus: Whether to always consider windows of this type focused.
        focus = true;
    };
};
```

**Comment by Dr-Dd** [comment]
Perfect, found out that the code was already present in the text but with opacity set to 0,75 and without any description. Thanks!
