### ISSUE TITLE
Compton doesn't work at all with mesa 18

### ISSUE THREAD

**Issue by g33kex** [chjj/compton#493]
Platform: Archlinux, kernel 4.16.8, amd64

GPU, drivers, and screen setup: Intel Integrated Graphics with i915 driver, i3 windows manager using X11

Compton version: 0.1_beta2.5-1 compiled from source via AUR

Compton configuration: https://pastebin.com/JSBvdnA6
(Same with any configuration)

### Steps of reproduction

Update Archlinux to the latest version with mesa 18, launch Compton with provided config/with any config

### Expected behavior

With the provided config, windows should have a transparency effect, there should be a fading effect when opening/closing windows, vsync, ...

### Current Behavior & Other details

Instead, nothing happens when compton is launched, with no error message, as if compton wasn't launched, even if it is.

**Comment by ghost** [comment]
This doesn't add up. This repository doesn't have a beta2.5 tag. I suspect you are using the yshui fork, which is used by the official Arch package: https://github.com/yshui/compton

You should open your issue against the source repo you are using.

**Comment by g33kex** [comment]
Sorry for the misunderstanding, actually the version is git-v0.1_beta2-87-g316eac0-2017-04-30 according to compton -v, I've pasted the version that pacman seems that seem to be wrong. It's compiled and installed using AUR from this repo. 

However, it seems that the issue is related to the glx backend, with the i915 driver, as the problem disappears if I switch the nvidia discrete graphic card.

**Comment by g33kex** [comment]
Selecting xrender backend works fine. I think it may be related to #477 and #487 except they're all using an AMD graphic card. It seems that with an intel graphic card, the glx backend doesn't work at all. Anybody also using intel i915 with compton and glx backend ?

**Comment by yshui** [comment]
@tourdetour Could you give [yshui/compton](https://github.com/yshui/compton) a try?

**Comment by g33kex** [comment]
Same issue with yushi/compton just compiled from source. I've also tried the version from the official arch community repo, same problem.

**Comment by yshui** [comment]
@tourdetour Sorry. Wasn't aware that you are using my fork.

This is weird. I have almost exactly the same setup (awesome instead of i3), but compton works fine here. Is compton the only package you updated recently?

**Comment by smlx** [comment]
> Anybody also using intel i915 with compton and glx backend

I am, and it's been working fine for a few years now.

This may be a problem specific to mesa 18, because I'm still on 13. I notice the other bugs are also on Arch, so likely running mesa 18 too.

What does `glxinfo | head` say?

**Comment by g33kex** [comment]
I tried both your fork and this version before posting. All my packages are up to date, and downgrading to mesa 17.3.7 fixes the issue. 

It seems to be a specific problem with mesa 18. 

`glxinfo` (with i915) says :

> name of display: :0
munmap_chunk(): invalid pointer
[1]    22775 abort (core dumped)  glxinfo`

`primusrun glxinfo | head` (with nvidia) says : 
> name of display: :0
 display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context,
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile,
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float,
    GLX_ARB_multisample, GLX_EXT_buffer_age,

**Comment by yshui** [comment]
@tourdetour glxinfo crashed, that's probably a bug in mesa, or a problem with your setup.

BTW, you never mentioned you are running on an Optimus setup?

**Comment by smlx** [comment]
Pretty certain we can close this issue - it's a bug in the Arch mesa 18 packages.

**Comment by g33kex** [comment]
@yshui I'm using an Optimus setup, but the selection between the two cards work fine, and even with nvidia driver blacklisted, the issue persists. 
@smlx It seems so. Should I report that to mesa 18?
