### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by avindra** [chjj/compton#501]
An official release has not been tagged in a few years. 

I think it would be helpful to tag a specific release, as various linux distributions are now using random revisions of compton.

Even if it's something as simple as releasing the current HEAD of master as `0.2.0`

Thanks.

**Comment by yshui** [comment]
@avindra I doubt there will be any more releases coming out of this repo.

**Comment by avindra** [comment]
@yshui do you mean to say that development has moved somewhere else?

**Comment by yshui** [comment]
@avindra I think the original developer has probably abandoned this project, given they have not made any commits in over a year, nor have they responded to any issues.

**Comment by jEsuSdA** [comment]
@avindra , @yshui , there is a fork that is in active development:
https://github.com/yshui/compton

**Comment by avindra** [comment]
ok looks like yshui did it. i'm closing this. thanks everyone!
