### ISSUE TITLE
Firefox address bar issue with inactive-dim

### ISSUE THREAD

**Issue by charlesvdv** [chjj/compton#504]
Platform: ArchLinux

GPU, drivers, and screen setup: Intel graphics with one monitor 

Compton version: v0.1_beta2.5 from Arch repo  

Compton configuration: see bottom 

### Steps of reproduction

1. Get firefox into focus
2. Click on the address bar
3. Type something

### Expected behavior

The address bar autocompletion dropdown shouldn't be dimmed as firefox is in focus. 

### Current Behavior & Other details

The address bar autocompletion dropdown is dimmed just like an inactive window even when I click on it. Every other dropdowns don't have any issue and are rendered properly. 

![test](https://user-images.githubusercontent.com/14892338/42453593-856841e4-838d-11e8-812c-258da2ba666d.png)

### Current config

```
shadow = false;
inactive-dim = 0.25;
inactive-dim-fixed = true;
detect-rounded-corners = true;

focus-exclude = [
   "class_g *= 'Firefox' && argb",
   "class_g = 'dmenu'",
   "class_g = 'mpv'"
];
```

---

Thanks!

**Comment by smlx** [comment]
Try this:

    mark-ovredir-focused = true;

**Comment by charlesvdv** [comment]
It works! Thanks a lot for your help!
