### ISSUE TITLE
Compton crashes when the screen is turned off

### ISSUE THREAD

**Issue by nlambert** [chjj/compton#533]
Platform: x86_64 Linux 4.19.8-arch1-1-ARCH Running i3-gaps

 GPU, drivers, and screen setup: Integrated Intel Graphics i7 8700k

Compton version: 4.0-1

Compton configuration: https://pastebin.com/r0BsbsmM

### Steps of reproduction

- Run compton (`compton -S --show-all-xerrors`)
- notice nice shadows and cool looking stuff
- turn screen off
- turn screen on
- notice compton has crashed (`ev_screen_change_notify(): Refresh rate detection failed, --sw-opti disabled.[1]    30341 floating point exception (core dumped)  compton -S --show-all-xerrors`)

### Expected behavior

No crash

Hopefully the problem isn't between the screen and the chair ;-)

**Comment by yshui** [comment]
@nlambert This bug belongs to [yshui/compton](/yshui/compton)

And this should be fixed by latest `next`

**Comment by nlambert** [comment]
Good to know @yshui. Just read your readme. And, yes, it is fixed in the latest `next`!
