### ISSUE TITLE
compton draining entire RAM

### ISSUE THREAD

**Issue by vikigenius** [chjj/compton#534]
Platform: GNU/Linux 4.19.9_1 i3wm 4.16 

GPU, drivers, and screen setup: INTEL UHD 620 (rev07)
Compton version: v3

Compton configuration: https://pastebin.com/LjdVQpu4
### Steps of reproduction

Starting compton with the standard options and waiting over a long period of time (2 - 3 hours) progressively drains RAM. 

### Expected behavior

Compton shouldn't use 4GB of RAM for standard use

### Current Behavior & Other details
After 2 hours, compton is already using 4GB of RAM. Using a Lenovo T480s without a DGPU, so only Intel Drivers.

**Comment by yshui** [comment]
@vikigenius This bug belongs to [yshui/compton](/yshui/compton).

And, can you try the latest release (v4) and see if that fix your problem?

**Comment by vikigenius** [comment]
Thanks, and the issue is resolved in the new version.
