### ISSUE TITLE
vsync option will take a boolean from now on

### ISSUE THREAD

**Issue by Moret84** [chjj/compton#543]
Platform: Archlinux

GPU, drivers, and screen setup:  NVidia GTX 1080, nvidia-drivers 418.56-1, MSI Optix G24C 

Compton version: 6.0-1 from distribution repos.

Compton configuration: https://pastebin.com/J88b1aB2

### Steps of reproduction

Just launch compton without any flag.

### Expected behavior

The software launch without warning.

### Current Behavior & Other details

I get the following message: 
[ 24/03/2019 17:30:19.255 parse_config_libconfig WARN ] vsync option will take a boolean from now on. "opengl-swc" is interpreted as "true" for compatibility, but this will stop working soon.

This is not compliant with what we can found in the [`wiki`](https://github.com/chjj/compton/wiki/vsync-guide).

How are we supposed to set the vsync mode right now ?

The error occurs when we set the vsync mode from the command line too but the error message is a quite cryptic "compton doesn't accept positional arguments."

**Comment by eoli3n** [comment]
Same here 
```
❯ compton --backend glx --vsync opengl-swc -GCb --config ~/.compton &
Job 1, 'compton --backend glx --vsync o…' has ended
compton doesn't accept positional arguments.
```

**Comment by JohnAZoidberg** [comment]
Arch doesn't use this project anymore. It has moved on to https://github.com/yshui/compton

**Comment by sgowie** [comment]
> 
> How are we supposed to set the vsync mode right now ?
> 

The `true` flag results in Compton picking the "best" vsync option for the user's environment
https://github.com/yshui/compton/commit/cebe1b18d664504e88fd67ac44f0dcbdce702ee7
