### ISSUE TITLE
Exclude certain windows from inactive-dim?

### ISSUE THREAD

**Issue by GOKOP** [chjj/compton#552]
So I want inactive windows to be dimmed. I know that `mark-ovredir-focused` causes all windows to be considered active on bspwm, due to the way bspwm works. Disabling this option however causes compton to dim conky windows and that looks rather ugly so I was thinking, is there a way to exclude conky windows from dimming?

**Comment by eepykate** [comment]
Does something like this work?
```
focus-exclude = [ 
	"class_g = 'mpv'",
];
```

**Comment by GOKOP** [comment]
Yes it does! Thanks
