### ISSUE TITLE
Default config with `glx-copy-from-front = true;` tells that option was removed.

### ISSUE THREAD

**Issue by WloHu** [chjj/compton#553]
Platform: Arch Linux
GPU, drivers, and screen setup: Intel HD 4000, mesa, 1 non-laptop screen turned on.
Compton version: 6.2-2

Compton configuration: Copied from "/etc/xdg/compton.conf". Changed lines:
```
glx-copy-from-front = true;
shadow-opacity = 0.8;
shadow-red = 1.0;
```

### Steps of reproduction
1. Copy default config to e.g. "~/.config/compton.conf".
1. Run compton through terminal. 
1. Change `glx-copy-from-front` to `true`.
1. Run in terminal `pkill compton && compton &`.

### Expected behavior
Current Behavior doesn't occur. Configuration option doesn't exist.
I don't know what else to expect because I was just testing out configuration to see what happens.

### Current Behavior & Other details
Error in terminal where Step 4. was run:
```
[ 07/01/2019 07:46:13.974 parse_config_libconfig ERROR ] "glx-copy-from-front" has been removed. If you encounter problems without this feature, please feel free to open a bug report
[ 07/01/2019 07:46:13.974 main FATAL ERROR ] Failed to create new compton session.
```

### Description
If the option "was removed" then it shouldn't be in default configuration in most recent version.

**Comment by WloHu** [comment]
I've also uncommented `glx-use-copysubbuffermesa` and I've had similar error. These 2 options aren't even available in `man` pages.

**Comment by nameless3** [comment]
Arch has switched to the [https://github.com/yshui/compton](https://github.com/yshui/compton) fork, which removed those options. 

Arch is shipping [https://git.archlinux.org/svntogit/community.git/tree/trunk/compton.conf?h=packages/compton](https://git.archlinux.org/svntogit/community.git/tree/trunk/compton.conf?h=packages/compton) which should be updated.

**Comment by WloHu** [comment]
@nameless3 Should I request this to Arch package maintainer? Should I close this issue?

**Comment by nameless3** [comment]
Yes, that sounds reasonable to me.

**Comment by WloHu** [comment]
The package was recently marked as outdated: 
![20190723_201252](https://user-images.githubusercontent.com/22800245/61736566-a95a4880-ad86-11e9-9978-40e67a3bea0e.png)
https://www.archlinux.org/packages/community/x86_64/compton/

When creating a new issue there is a notice: "REPEAT: Do NOT report bugs for outdated packages!" so I think there is nothing to do for now. I will link the bug report here if updating the packange won't solve the issue.

Closing.
