### ISSUE TITLE
Invalid blur method kawase

### ISSUE THREAD

**Issue by logicguy1** [chjj/compton#579]
Hello! 

So im following a tutorial by Avahe Kellenberger you can find it [here](https://www.youtube.com/watch?v=Qng0lPIat-Y&t=66s)

My config currently looks like this and my goal is to get a blurred background on transparent windows :)
![image](https://user-images.githubusercontent.com/56993729/140642414-e93da00c-d4a8-41be-8825-f28be372546a.png)

The issue im running into is when activating compton i gett this fatal error:
![image](https://user-images.githubusercontent.com/56993729/140642433-e80ca093-f023-4ed1-a688-c8ceaf4b25b4.png)
Any help would be apprechiated

**Comment by SkyyySi** [comment]
Kawase is not supported in this branch. Compton has been dead since 2017. It's replacement is a fork called picom.

**Comment by logicguy1** [comment]
I found picom, noticed the age of the project xd
