### ISSUE TITLE
Make doesnt install

### ISSUE THREAD

**Issue by miranyx** [chjj/compton#580]
Platform: PopOs 2104 amd64 

GPU, drivers, and screen setup: NVidia RTX 2070, two monitors configured side-by-side

Compton version: Current

Compton configuration: <Fresh clone

### Steps of reproduction

First I run make then I run make docs then I get this: 

a2x --format manpage man/compton.1.asciidoc
make: a2x: No such file or directory
make: *** [Makefile:146: man/compton.1] Error 127

the same for make install.

### Expected behavior

It installs it

### Current Behavior & Other details

It does not install it.

**Comment by SkyyySi** [comment]
No issues will be resolved in this repository. Compton has been dead since 2017. It's replacement is a fork called picom.
