### ISSUE TITLE
Feature: Blur

### ISSUE THREAD

**Issue by Janhouse** [chjj/compton#69]
Could someone implement window background blur for transparent windows?

**Comment by jEsuSdA** [comment]
Hi!

Can anyone tell me how I can disable the blur-background feature for popup menus?

For example, here you can see how the menu and popup of any GTK3 app is blurred:

![imagen](https://user-images.githubusercontent.com/5833446/44467757-f5a38280-a623-11e8-9ed7-4c2228335e50.png)

Thanks!

**Comment by WuerfelDev** [comment]
I'm trying to write something similar to
> `./compton --opengl --sw-opti --vsync opengl-swc --paint-on-overlay -cCGb -r 10 -o 0.5 -l-12 -t-12 -fF -D35 -I0.4 -O0.4 --blur-background`

in the compton.conf, but how can I set the flag `--opengl` there?
