### ISSUE TITLE
lose focused window in i3 for transparency

### ISSUE THREAD

**Issue by daBrado** [chjj/compton#99]
I use compton to dim and make transparent unfocused windows.  In i3, sometimes when closing all but the last window, that last window gains focus but compton for some reason doesn't realize this and it remains transparent.

This had not been happening until I updated recently-ish.

I haven't yet found a reliable way to recreate this... sorry that I don't have much data... just thought I'd get the issue posted in case you had an idea of what might have happened.

Let me know if you have a good way for me to help debug this.

**Comment by amosbird** [comment]
I'm seeing similar issue in bspwm. It's very easy to reproduce. With compton config like this
```
inactive-opacity = 0.8;
```
Reproduce steps:
1. generating a floating window and get its window id
2. setup a key binding that execute this command `bspc node $id -g hidden -f`
3. focusing on a tile window and start pressing that key binding. When the tile window regain focus, it remains transparent.

env:

compton v0.1_beta2.5
bspwm 0.9.5
archlinux
